#!/usr/bin/env node
/**
 * dsh-all-in-one aggregate generator.
 *
 * Reads ./aggregate.yml and deterministically produces:
 *   1. package.json  -> "dependencies" block (exact pins per plugin channel)
 *   2. cordis.patch.yml -> one guarded insert row per aggregated plugin,
 *      plus manifest extraRows (e.g. the session-title-llm disable).
 *
 * Usage:
 *   node scripts/aggregate.mjs           regenerate both outputs
 *   node scripts/aggregate.mjs --verify  fail if outputs drifted from disk
 *
 * The generated patch is consumed by the DSH profile boot. Row semantics:
 * each row re-uses the plugin's canonical standalone ID so profile-patch
 * config overrides keep working, and carries a !!js back-off guard so the
 * row disables itself whenever an EARLIER loader entry already mounts the
 * same package under a different ID (standalone installs win; because
 * `dsh plugin add` appends bundles last, the suite's rows are evaluated
 * after any standalone rows and can see them).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { parse, stringify } from 'yaml';

const manifestPath = new URL('../aggregate.yml', import.meta.url);
const pkgPath = new URL('../package.json', import.meta.url);
const patchPath = new URL('../cordis.patch.yml', import.meta.url);

const verifyOnly = process.argv.includes('--verify');

const manifest = parse(readFileSync(manifestPath, 'utf8'));

// --- validate ---------------------------------------------------------------
const plugins = manifest.plugins ?? [];
const seenIds = new Map();
const seenPkgs = new Map();
for (const p of plugins) {
  if (!p.package || typeof p.package !== 'string') throw new Error('plugin without package name');
  if (!p.id || typeof p.id !== 'string') throw new Error(`plugin ${p.package} without row id`);
  if (seenIds.has(p.id)) throw new Error(`duplicate row id '${p.id}' (${seenIds.get(p.id)} also uses it)`);
  if (seenPkgs.has(p.package)) throw new Error(`duplicate package '${p.package}'`);
  seenIds.set(p.id, p.package);
  seenPkgs.set(p.package, p.id);
  if (!['npm', 'github-release'].includes(p.channel)) {
    throw new Error(`plugin ${p.package}: unsupported channel '${p.channel}'`);
  }
  if (p.enabled === false) continue;
  if (p.channel === 'npm' && !p.version) throw new Error(`plugin ${p.package}: npm channel requires exact version`);
  if (p.channel === 'github-release' && !p.spec) throw new Error(`plugin ${p.package}: github-release channel requires spec URL`);
}
if (!manifest.package?.name || !manifest.package?.version) {
  throw new Error('manifest.package.name / .version are required');
}

const enabled = plugins.filter((p) => p.enabled !== false);

function dependencySpec(p) {
  return p.spec ?? String(p.version);
}

// --- dependencies -----------------------------------------------------------
const deps = {};
for (const p of [...enabled].sort((a, b) => a.package.localeCompare(b.package))) {
  deps[p.package] = dependencySpec(p);
}

const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
pkg.dependencies = deps;
const nextPkgText = JSON.stringify(pkg, null, 2) + '\n';

// --- patch ------------------------------------------------------------------
/** Quote a scalar for YAML when it could be misread (scoped names start with @). */
function ystr(value) {
  return value.startsWith('@') ? `'${value}'` : value;
}

function guardedRow(p) {
  const expr =
    `[...ctx.loader.entries()].some((entry) => entry.options.name === '${p.package}' && ` +
    `entry.options.id !== '${p.id}' && !entry.disabled)`;
  return [
    `    - id: ${p.id}`,
    `      name: ${ystr(p.package)}`,
    `      disabled: !!js "${expr}"`,
  ];
}

function extraRowLines(row) {
  if (row.requiresPlugin) {
    const dep = plugins.find((p) => p.package === row.requiresPlugin);
    if (!dep) throw new Error(`extraRows.requiresPlugin references unknown package ${row.requiresPlugin}`);
    if (dep.enabled === false) return [];
  }
  // Reuse the yaml lib for arbitrary user-provided entries, then indent them
  // one level under a bare top-level list item.
  return stringify([row.entry]).trimEnd().split('\n');
}

const lines = [];
lines.push('# AUTO-GENERATED by scripts/aggregate.mjs -- do not edit.');
lines.push('# Source of truth: aggregate.yml (pnpm generate).');
lines.push('#');
lines.push(`# Aggregates ${enabled.length} DSH plugins into one bundle row set. IDs are each`);
lines.push("# plugin's canonical standalone ID so existing profile-patch overrides keep");
lines.push('# applying unchanged. Every insert backs itself off when an earlier entry');
lines.push('# already mounts the same package (standalone installs win). Install order');
lines.push('# caveat: guards only see earlier entries; "dsh plugin add" appends this');
lines.push('# bundle last, which is the supported configuration.');
lines.push('');

let wroteExtra = false;
for (const row of manifest.extraRows ?? []) {
  const body = extraRowLines(row);
  if (body.length === 0) continue;
  if (!wroteExtra) {
    lines.push('# Manifest extra rows (conditional on their required plugin being enabled).');
    wroteExtra = true;
  }
  lines.push(...body);
  lines.push('');
}

for (const p of enabled) {
  lines.push('- insert:');
  lines.push(...guardedRow(p));
  lines.push('');
}

let nextPatchText = lines.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';
if (!wroteExtra) {
  // keep header + blank separation tidy even without extra rows
  nextPatchText = nextPatchText;
}

// --- write or verify --------------------------------------------------------
let drift = false;

const currentPkgText = readFileSync(pkgPath, 'utf8');
if (currentPkgText !== nextPkgText) {
  if (verifyOnly) {
    console.error('DRIFT: package.json dependencies differ from aggregate.yml.');
    drift = true;
  } else {
    writeFileSync(pkgPath, nextPkgText);
    console.log('package.json: dependencies updated.');
  }
} else {
  console.log('package.json: up to date.');
}

let currentPatchText = null;
try {
  currentPatchText = readFileSync(patchPath, 'utf8');
} catch {
  // first run: the patch does not exist yet
}
if (currentPatchText !== nextPatchText) {
  if (verifyOnly) {
    console.error(currentPatchText === null
      ? 'DRIFT: cordis.patch.yml is missing; run "pnpm generate".'
      : 'DRIFT: cordis.patch.yml differs from aggregate.yml output.');
    drift = true;
  } else {
    writeFileSync(patchPath, nextPatchText);
    console.log(currentPatchText === null ? 'cordis.patch.yml: created.' : 'cordis.patch.yml: regenerated.');
  }
} else {
  console.log('cordis.patch.yml: up to date.');
}

console.log(`aggregated plugins: ${enabled.map((p) => p.package).join(', ')}`);

if (drift) process.exit(1);
